# Generated by Django 6.0.3 on 2026-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefeedback',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('FIN', 'Finance'), ('HR', 'Human Resources'), ('PM', 'Project Management')], max_length=10),
        ),
    ]
